</head>

<body>
    <div class="dash-container">
        <div class="navbar-container">
            <div class="logo">
                <span class="web-logo"><i class="fas fa-dumbbell"></i></span> 
                <span class="logo-title">sport</span>
            </div>
            <ul class="nav-list">
                <li class="list-item">
                    <a data-name="dashboard.php" class="nav-btn " href="dashboard.php">
                        <span><i class="fas fa-home"></i></span> 
                        <span class="nav-btn-title">home page</span>
                    </a>
                </li>
                <li class="list-item">
                    <a data-name="trainees.php" class="nav-btn" href="trainees.php">
                        <span><i class="fas fa-running"></i></span> 
                        <span class="nav-btn-title">trainees</span>
                    </a>
                </li>
                <li class="list-item">
                    <a data-name="trainers.php" class="nav-btn" href="trainers.php">
                        <span><i class="fas fa-user"></i></span> 
                        <span class="nav-btn-title">trainers</span>
                    </a>
                </li>
                <li class="list-item">
                    <a data-name="Nutritionists.php" class="nav-btn" href="Nutritionists.php">
                        <span><i class="fas fa-user-md"></i></span> 
                        <span class="nav-btn-title">Nutritionists</span>
                    </a>
                </li>
                <li class="list-item">
                    <a data-name="sections.php" class="nav-btn" href="sections.php">
                        <span><i class="fas fa-clone"></i></span> 
                        <span class="nav-btn-title">Section</span>
                    </a>
                </li>
                <li class="list-item">
                    <a data-name="posts.php" class="nav-btn" href="posts.php">
                        <span><i class="fas fa-comment-alt"></i></span> 
                        <span class="nav-btn-title">posts</span>
                    </a>
                </li>
                <li class="list-item">
                    <a data-name="payments.php" class="nav-btn" href="payments.php">
                        <span> <i class="fas fa-credit-card"></i></span> 
                        <span class="nav-btn-title">payments</span>
                    </a>
                </li>
                <li class="list-item">
                    <a data-name="../website/sign-out.php" class="nav-btn" href="../website/sign-out.php">
                        <span> <i class="fas fa-sign-out-alt"></i></span> 
                        <span class="nav-btn-title">logout</span>
                    </a>
                </li>
            </ul>
        </div>
